In [1]:
from kmcluster.core.data import sparse_to_mat
Pt_H1_links = [
    [0, 1, 0.15],
    [0, 2, 0.61],
    [0, 3, 0.39],
    [2, 4, 0.27],
    [2, 6, 0.50],
    [2, 8, 0.66],
    [3, 8, 0.50],
    [5, 7, 0.52],
    [5, 9, 0.66],
    [5, 6, 0.66],
]
H_H1_links = [
    [0, 6, 0.52],
    [1, 2, 0.28],
    [2, 5, 0.22],
    [3, 5, 0.22],
    [7, 8, 0.15],
    [8, 9, 0.14],
]
Pt4H1_rawE = [
    -17.71720725,
    -17.68531409,
    -17.57336808,
    -17.50640668,
    -17.50097929,
    -17.50887522,
    -17.38155630,
    -17.25580137,
    -17.15164472,
    -17.13649884,
]
H1_E = [Pt4H1_rawE[x] - Pt4H1_rawE[0] for x in range(0, len(Pt4H1_rawE))]

Pt4H1_rev = []
for i in range(0, len(Pt_H1_links)):
    Pt4H1_rev.append(
        [
            Pt_H1_links[i][1],
            Pt_H1_links[i][0],
            round(
                (Pt_H1_links[i][2] + H1_E[Pt_H1_links[i][0]]) - H1_E[Pt_H1_links[i][1]],
                2,
            ),
        ]
    )

# raw energies
Pt4H1_rawE = [
    -17.71720725,
    -17.68531409,
    -17.57336808,
    -17.50640668,
    -17.50097929,
    -17.50887522,
    -17.38155630,
    -17.25580137,
    -17.15164472,
    -17.13649884,
]

# relative energies
H1_E = [Pt4H1_rawE[x] - Pt4H1_rawE[0] for x in range(0, len(Pt4H1_rawE))]

# all the forward barriers
Pt_H1_links = [
    [0, 1, 0.15],
    [0, 2, 0.61],
    [0, 3, 0.39],
    [2, 4, 0.27],
    [2, 6, 0.50],
    [2, 8, 0.66],
    [3, 8, 0.55],
    [5, 7, 0.52],
    [5, 9, 0.66],
    [5, 6, 0.66],
    [0, 6, 0.52],
    [1, 2, 0.28],
    [2, 5, 0.22],
    [3, 5, 0.22],
    [7, 8, 0.15],
    [8, 9, 0.14],
]

# calculating the reverse barriers
Pt4H1_rev = []
for i in range(0, len(Pt_H1_links)):
    Pt4H1_rev.append(
        [
            Pt_H1_links[i][1],
            Pt_H1_links[i][0],
            round(
                (Pt_H1_links[i][2] + H1_E[Pt_H1_links[i][0]]) - H1_E[Pt_H1_links[i][1]],
                2,
            ),
        ]
    )

# all barriers
Pt_H1_all = Pt_H1_links + Pt4H1_rev
energies_mat = sparse_to_mat(Pt_H1_all)

In [6]:
import numpy as np 
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})


[[0.00 0.15 0.61 0.39 0.00 0.00 0.52 0.00 0.00 0.00]
 [0.12 0.00 0.28 0.00 0.00 0.00 0.00 0.00 0.00 0.00]
 [0.47 0.17 0.00 0.00 0.27 0.22 0.50 0.00 0.66 0.00]
 [0.18 0.00 0.00 0.00 0.00 0.22 0.00 0.00 0.55 0.00]
 [0.00 0.00 0.20 0.00 0.00 0.00 0.00 0.00 0.00 0.00]
 [0.00 0.00 0.16 0.22 0.00 0.00 0.66 0.52 0.00 0.66]
 [0.18 0.00 0.31 0.00 0.00 0.53 0.00 0.00 0.00 0.00]
 [0.00 0.00 0.00 0.00 0.00 0.27 0.00 0.00 0.15 0.00]
 [0.00 0.00 0.24 0.20 0.00 0.00 0.00 0.05 0.00 0.14]
 [0.00 0.00 0.00 0.00 0.00 0.29 0.00 0.00 0.12 0.00]]
[[0.00 57391.48 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00]
 [1865689.41 0.00 0.02 0.00 0.00 0.00 0.00 0.00 0.00 0.00]
 [0.00 5634.47 0.00 0.00 0.05 17.02 0.00 0.00 0.00 0.00]
 [1765.45 0.00 0.00 0.00 0.00 17.02 0.00 0.00 0.00 0.00]
 [0.00 0.00 173.32 0.00 0.00 0.00 0.00 0.00 0.00 0.00]
 [0.00 0.00 17982.50 17.02 0.00 0.00 0.00 0.00 0.00 0.00]
 [1765.45 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00]
 [0.00 0.00 0.00 0.00 0.00 0.05 0.00 0.00 57391.48 0.00]
 [0.00 0.00 1

In [2]:
from kmcluster.core.kmc import kmc 
from kmcluster.core.transition_conditions import rfkmc
from kmcluster.core.intialize import random_init, boltz
from kmcluster.core.data import sparse_to_mat

T_kelvin = 100
temp_boltz = T_kelvin * 8.617 * 10 ** (-5)
rfkmc_obj = rfkmc(k_b_t=temp_boltz, energy_mat=energies_mat)
#time_stop = 0.001
init_boltz = boltz(energies=H1_E, T=temp_boltz, size=10000)
init_random = random_init(10000, energies_mat.shape[0])
# initialize kmc object
kmc_boltz = kmc(
    time_stop=0.0001,
    energies=energies_mat,
    draw_crit=rfkmc_obj,
    initialization=init_random,
    memory_friendly=False
)


# run calcs
# can either run to a certain number of steps or until a certain time
# n_steps=-1 means run until time_stop is reached
kmc_boltz.run(n_steps=-1)
# kmc_boltz.run(n_steps=100)
trajectories = kmc_boltz.trajectories

0.0
0.15
0.61
0.39
0.0
0.0
0.52
0.0
0.0
0.0
0.12
0.0
0.28
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.47
0.17
0.0
0.0
0.27
0.22
0.5
0.0
0.66
0.0
0.18
0.0
0.0
0.0
0.0
0.22
0.0
0.0
0.55
0.0
0.0
0.0
0.2
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.16
0.22
0.0
0.0
0.66
0.52
0.0
0.66
0.18
0.0
0.31
0.0
0.0
0.53
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.27
0.0
0.0
0.15
0.0
0.0
0.0
0.24
0.2
0.0
0.0
0.0
0.05
0.0
0.14
0.0
0.0
0.0
0.0
0.0
0.29
0.0
0.0
0.12
0.0
initialization proportions
{0: 1010, 1: 1023, 2: 996, 3: 1008, 4: 999, 5: 982, 6: 971, 7: 1011, 8: 1053, 9: 947}
Lowest time at step 0: 0.00000e+00

Saving to file: ./checkpoints/saved_data_trajectories_1_final_ckpt_start_0_end_1.00000e-04_step_1.00000e-06
Lowest time at final step 36: 9.54937e-05



In [3]:
kmc_boltz.plot_top_n_states_stacked(
    n_show = -1,
    resolution=0.000001, 
    max_time=0.0001, 
    title=None, 
    save=False, 
    save_name="props.png")

/home/santiagovargas/dev/kmcluster/kmcluster/core/kmc.py:428: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_new_format = df_new_format.append(pd.DataFrame({'time': df.columns, 'state': df.index[i], 'percentage': df.iloc[i, :]}))
/home/santiagovargas/dev/kmcluster/kmcluster/core/kmc.py:428: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_new_format = df_new_format.append(pd.DataFrame({'time': df.columns, 'state': df.index[i], 'percentage': df.iloc[i, :]}))
/home/santiagovargas/dev/kmcluster/kmcluster/core/kmc.py:428: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_new_format = df_new_format.append(pd.DataFrame({'time': df.columns, 'state': df.index[i], 'percentage': df.iloc[i, :]}))
/home/santiagovargas/dev/kmcluster/km